### ISSUE TITLE
functions in cmd table are not running

### ISSUE THREAD

**Issue by ahmedelgabri** [lukas-reineke/format.nvim#1]
This is the config I'm testing & I have `g:format_debug=v:true`

This works fine

```lua
require "format".setup {
  typescript = {
    {cmd = {"prettier -w"}}
  }
}
```

This doesn't run

```lua
require "format".setup {
  typescript = {
    cmd = {
      function(file)
        return string.format("prettier --print-width %s -w %s", vim.bo.textwidth, file)
      end
    }
  }
}
```

**Comment by lukas-reineke** [comment]
Your second example is missing one set of `{}`

```
require "format".setup {
    typescript = {
        {
            cmd = {
                function(file)
                    return string.format("prettier --print-width %s -w %s", vim.bo.textwidth, file)
                end
            }
        }
    }
}
```

It's a bit confusing. I'm not super happy with the structure. :thinking:

**Comment by ahmedelgabri** [comment]
Thanks, it might not be perfect but what's more important I think is that it shouldn't error silently because it's very hard to debug.

**Comment by lukas-reineke** [comment]
> it shouldn't error silently

yea I agree. I should write some validation logic to raise errors with invalid config.
