### ISSUE TITLE
[Feature Request] configure like neoformat

### ISSUE THREAD

**Issue by siduck76** [lukas-reineke/format.nvim#11]
Hi there, great plugin! Ive been using neoformat for a while now and it works well ootb  . I just have to install neoformat and :Neoformat for formatting stuff. It needs no config , it'd be nice if format.nvim implements something similar too so for example , just installing format.nvim and external dependencies could be very nicee and no user config unless the user wants to add his own stuff. 

check : https://github.com/sbdchd/neoformat/tree/master/autoload/neoformat/formatters 

https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/c.vim

**Comment by lukas-reineke** [comment]
No sorry, I am not interested in maintaining specific formatter configuration.

**Comment by siduck76** [comment]
> No sorry, I am not interested in maintaining specific formatter configuration.

I meant for almost all languages , Ik it'd be too much of a hassle but no worries!
