### ISSUE TITLE
Treesitter integration

### ISSUE THREAD

**Issue by colinxs** [lukas-reineke/format.nvim#13]
Instead of manually specifying `start_pattern` and `end_pattern`, have you thought about using Treesitter to detect embedded languages? That's already an inherent feature of Treesitter (and is used for highlighting said embedded languages). I know nvim-treesitter is still in it's early stages, but it's rock solid for most common languages.

**Comment by lukas-reineke** [comment]
I answered in formatter.nvim
If I implement this it will be over there, so closing it here
