### ISSUE TITLE
clang-format not working

### ISSUE THREAD

**Issue by alexzanderr** [lukas-reineke/format.nvim#14]
i have these:
```lua
require "format".setup {
	cpp = {{
			-- cmd = {"clang-format --style='{BasedOnStyle: chromium, IndentWidth: 4}'"}
			cmd = {"clang-format"}
	}},
	c = {{
			cmd = {"clang-format --style='{BasedOnStyle: chromium, IndentWidth: 4}'"}
	}},
}
```

calling clang-format like this in terminal works like a charm.

but calling from plugin with this config doesnt work.

help.

i've tested for `python` with `black` works like a charm and its really fast.

but it doesnt work for cpp/c ... :(

**Comment by lukas-reineke** [comment]
Not sure TBH, I don't use `clang-format`

I don't really maintain this plugin anymore. I ported everything I build here to https://github.com/mhartington/formatter.nvim
And I am a maintainer over there too.

I'd suggest you switch to use `formatter.nvim`, and there is a config example for `clang-format` https://github.com/mhartington/formatter.nvim/blob/master/CONFIG.md#clang-format

**Comment by alexzanderr** [comment]
> I'd suggest you switch to use formatter.nvim

yea, i just did that after raising this issue.

> there is a config example for clang-format

i've used that, its very fine.

my question is: is `formatter.nvim` async like your plugin, `format.nvim` ?

**Comment by lukas-reineke** [comment]
> my question is: is formatter.nvim async like your plugin, format.nvim ?

Yes it is. Both of them work basically the same, I wrote the async code for both.

**Comment by alexzanderr** [comment]
very nice. thank you
