### ISSUE TITLE
Will format.nvim auto change filename?

### ISSUE THREAD

**Issue by flaviusbuffon** [lukas-reineke/format.nvim#16]
I am using format.nvim and latexindent to beautify my tex code, but it is strange that there are many bak file created.

Latexindent log displayed that maybe format.nvim change filename when saving code like this :

![image](https://user-images.githubusercontent.com/44057232/145595321-4d2248bc-5377-4848-b85a-54e5e3855049.png)

**Comment by lukas-reineke** [comment]
It does not change the file name. It creates new temporary files to do the formatting.

**Comment by flaviusbuffon** [comment]
> It does not change the file name. It creates new temporary files to do the formatting.
how to disable it of tex filetype or repair it?

**Comment by lukas-reineke** [comment]
You can't disable it. This is how the plugin works.
You can try to not create backup files for them.

**Comment by flaviusbuffon** [comment]
The problem I need to solve now is how can I get the format to read the original filename in the format plugin configuration.
For example, for the main.tex file, what is the best way to represent this original file name?

![image](https://user-images.githubusercontent.com/44057232/145682116-de37fd28-4d51-4f6b-b7dd-04fc205899c9.png)

**Comment by lukas-reineke** [comment]
> The problem I need to solve now is how can I get the format to read the original filename in the format plugin configuration.

Why do you want to do that? I think you are misunderstanding something, what are you trying to achieve?

**Comment by flaviusbuffon** [comment]
pls try latexindent for a while, i just want to format tex file by latexindent.
Since format.nvim will create tmp file when formating , latexindent will format the tmp file rather than origin file. 
But actually, latexindent will make a backup when it is working.

**Comment by flaviusbuffon** [comment]
pls try latexindent for a while, i just want to format tex file by latexindent.
Since format.nvim will create tmp file when formating , latexindent will format the tmp file rather than origin file. 
But actually, latexindent will make a backup when it is working.

**Comment by lukas-reineke** [comment]
The plugin works by creating a temp file, formatting that, then writing the result back into the original file. To not block editing and to not save the actual file.

You cannot pass the actual file. This is by design.
If you need this, you'll have to use a different plugin

**Comment by flaviusbuffon** [comment]
i have understood what u said, thanks!
The only solution is to make latexindent do not create temp file
