### ISSUE TITLE
tempfile fails to open

### ISSUE THREAD

**Issue by lukas-reineke** [lukas-reineke/format.nvim#4]
Same here. I got the error message: Format error: ...o/.config/nvim/plugged/format.nvim/lua/format/format.lua:35: attempt to index local 'tempfile' (a nil value)

_Originally posted by @pulcinello in https://github.com/lukas-reineke/format.nvim/issues/3#issuecomment-717914995_

**Comment by elianiva** [comment]
I also got this message if I use `~` as a shorthand for home directory.  The solution is to replace it with `os.getenv("HOME").."/rest/of/directory"`.

**Comment by ndreas** [comment]
You also get this error when the file is in the same directory as the buffer's current path. I stumbled upon this when I tried the plugin, and I use `set autochdir`. The result here: https://github.com/lukas-reineke/format.nvim/blob/master/lua/format/format.lua#L30 will in that case be an empty table, and the generated temporary filename will be located in the filesystem root.

**Comment by lukas-reineke** [comment]
Thanks for the debugging
I pushed a fix

**Comment by ndreas** [comment]
> Thanks for the debugging
> I pushed a fix

That was fast! I was just about to create a PR :smile_cat: It works for me, and I got a bonus debug print statement :stuck_out_tongue_closed_eyes: https://github.com/lukas-reineke/format.nvim/commit/d4a9f7eac93320503267b5b0c32b7291aa7286f8#diff-b05a6a67438ba15eb301bf4568205cbd072768999217c5f3b379e07fafb9de3fR37

**Comment by lukas-reineke** [comment]
> and I got a bonus debug print statement
:facepalm: fixed
