### ISSUE TITLE
Is there a way to format without losing the jump history?

### ISSUE THREAD

**Issue by Furkanzmc** [lukas-reineke/format.nvim#6]
Hi Lukas.

Thanks for the plugin. I've been using it, favoring it over the LSP provided formatting. One thing I noticed that is common for both this and the LSP provided formatting is that the jump history is cleared when the file is formatted.

Is there a way to avoid that?

**Comment by lukas-reineke** [comment]
Thanks for the issue, I looked into it and there is a way to keep it.
But I don't think I will implement it here. I am working on porting everything I made here over to https://github.com/mhartington/formatter.nvim
I makes more sense to have only one good plugin.
But it's not quite done yet.

If you want to, you can take a look at the PR where I implemented it in formatter.nvim https://github.com/mhartington/formatter.nvim/pull/9

**Comment by Furkanzmc** [comment]
That makes sense. Thanks, I'll follow the progress there and until then keep using this plugin. Closing the issue.
