### ISSUE TITLE
extra key press after save 

### ISSUE THREAD

**Issue by caheredia** [lukas-reineke/format.nvim#7]
Hi, thanks again for the plug-in. After the latest update, I noticed have to press Enter after saving (and auto formatting). 
Is there a way to go back to the previous behavior where auto formatting doesn't ask me for an extra key press? 
<img width="937" alt="Screen Shot 2020-11-16 at 11 12 04 PM" src="https://user-images.githubusercontent.com/28638529/99357924-a2035c00-2861-11eb-9b90-16ba17f0d4d0.png">

These are the settings I used to invoke formatting 

```viml
" auto format and save
augroup Format
    autocmd!
    autocmd BufWritePost * FormatWrite
augroup END
```

**Comment by lukas-reineke** [comment]
:facepalm: I fixed that 2 weeks ago, but forgot to push

Should be fixed now :pray:

**Comment by caheredia** [comment]
awesome, thanks!
