### ISSUE TITLE
Format from stdout

### ISSUE THREAD

**Issue by Shatur95** [lukas-reineke/format.nvim#8]
I use `clang-format` and `lua-format`. Both programs print formatted text to stdout. Is it possible to support this behavior?

**Comment by lukas-reineke** [comment]
No I don't plan to add it here.
I have been working together with Mike on https://github.com/mhartington/formatter.nvim
That plugin should replace this one completely. I already ported all the features over, merging the PRs just takes some time.
It should hopefully be done soon. After that I will deprecate format.nvim 

You should be using that plugin, it supports stdout as well.

**Comment by Shatur95** [comment]
Thanks for the info!
