### ISSUE TITLE
This vs formatter.nvim

### ISSUE THREAD

**Issue by Dkendal** [lukas-reineke/format.nvim#9]
Hey, just curious what your view is on plans to develop this vs steering people to formatter.nvim?
The readme states that this started out as a PR to formatter.nvim, but I also see that you have commits in formatter.nvim that are newer than the most recent commits here.

Thanks!

**Comment by lukas-reineke** [comment]
I plan to deprecate this in favor of formatter.nvim
Probably once [this PR](https://github.com/mhartington/formatter.nvim/pull/19) is merged.
I am maintainer of formatter.nvim as well now and been working on moving all the features over.

**Comment by Dkendal** [comment]
Thanks for the clarification!

**Comment by 9mm** [comment]
hey @lukas-reineke I've read a lot of your posts regarding formatting. There is a lot to absorb, and there are a significant amount of points that are still unclear.

My goal is to do both linting + formatting in Neovim.

Linting:
* eslint non-formatting rules, 99% of the time
* golintci-lint

Formatting:
* prettier
* gofmt

The main part I'm confused on is what EFM is, and does it only help with formatting but not linting? I understand the difference between formatting and linting, but specifically in terms of some kind of generalized language server, they seem to be roughly the same (read code, write code)

Is EFM still the best choice in your opinion? How might one manage both formatting and linting with EFM, say... eslint + prettier?

**Comment by lukas-reineke** [comment]
EFM does linting too, you just need to specify the `lintCommand` and `lintFormats` so EFM understand the output. `lintFormats` is the same as `:help errorformat` (that's also where EFM gets its name from btw).

My setup for prettier and go looks like this

```lua
local prettier = {
    formatCommand = "prettier --stdin-filepath ${INPUT}",
    formatStdin = true,
}

local eslint = {
    lintCommand = "eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}",
    lintIgnoreExitCode = true,
    lintStdin = true,
    lintFormats = {
        "%f(%l,%c): %tarning %m",
        "%f(%l,%c): %rror %m",
    },
    lintSource = "eslint",
}

local govet = {
    lintCommand = "go vet",
    lintIgnoreExitCode = true,
    lintFormats = { "%f:%l:%c: %m" },
    lintSource = "go vet",
}

local goimports = {
    formatCommand = "goimports",
    formatStdin = true,
}

local staticcheck = {
    lintCommand = "staticcheck",
    lintIgnoreExitCode = true,
    lintFormats = { "%f:%l:%c: %m" },
    lintSource = "staticcheck",
}

local languages = {
    typescript = { prettier, eslint },
    go = { staticcheck, goimports, govet },
}

require("lspconfig").efm.setup {
    init_options = { documentFormatting = true },
    root_dir = vim.loop.cwd,
    filetypes = vim.tbl_keys(languages),
    settings = {
        rootMarkers = { ".git/" },
        lintDebounce = "500ms",
        languages = languages,
    },
}
```

**Comment by 9mm** [comment]
awesome,... thats very helpful. Thank you!
